# Generated by Django 2.2.11 on 2020-03-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20170720_1704'),
        ('request', '0006_alter_request_method_default'),
    ]

    operations = [
    ]
